<a href="https://colab.research.google.com/github/jenous11/CRUD-application-in-php/blob/main/workingwithkaggle_parsed_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
uploaded_files=files.upload()

Saving kaggle_parsed_dataset.csv to kaggle_parsed_dataset.csv

In [3]:
kaggle_df=pd.read_csv("kaggle_parsed_dataset.csv")

In [4]:
kaggle_df.head(5)

,index,oh_label,Date,Text
0,0,1,20120618192155Z,"""You fuck your dad."""
1,1,0,20120528192215Z,"""i really don't understand your point.\xa0 It ..."
2,2,0,NaN,"""A\\xc2\\xa0majority of Canadians can and has ..."
3,3,0,NaN,"""listen if you dont wanna get married to a man..."
4,4,0,20120619094753Z,"""C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd..."

In [5]:
kaggle_df.isnull().sum()

index          0
oh_label       0
Date        1242
Text           0
dtype: int64

In [6]:
print(kaggle_df.shape)

(8799, 4)

In [7]:
# checking for missing data

print("Missing Text:", kaggle_df['Text'].isna().sum())
print("\nLabel distribution:\n")
print(kaggle_df['oh_label'].value_counts())

Missing Text: 0

Label distribution:

oh_label
0    5993
1    2806
Name: count, dtype: int64

In [8]:
#cleaning the empty cells

In [9]:
kaggle_clean=kaggle_df[['Text','oh_label']].copy()

In [10]:
# kaggle_clean=kaggle_clean.dropna(subset=['Text','oh_label'])
kaggle_clean=kaggle_clean.dropna(subset=['Text','oh_label'])
kaggle_clean

                                                   Text  oh_label
0                                  "You fuck your dad."         1
1     "i really don't understand your point.\xa0 It ...         0
2     "A\\xc2\\xa0majority of Canadians can and has ...         0
3     "listen if you dont wanna get married to a man...         0
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...         0
...                                                 ...       ...
8794  "Never really gave it much thought. I just fig...         0
8795                 "Nadie se salva de la regla 34 xd"         0
8796               "Question: Are you a boy or a girl?"         0
8797  "Leave your email or phone number and maybe yo...         1
8798  "From the scenarios you present, I see you bel...         0

[8799 rows x 2 columns]

In [11]:
kaggle_clean=kaggle_clean.rename(columns={'oh_label':'label'})
kaggle_clean

                                                   Text  label
0                                  "You fuck your dad."      1
1     "i really don't understand your point.\xa0 It ...      0
2     "A\\xc2\\xa0majority of Canadians can and has ...      0
3     "listen if you dont wanna get married to a man...      0
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...      0
...                                                 ...    ...
8794  "Never really gave it much thought. I just fig...      0
8795                 "Nadie se salva de la regla 34 xd"      0
8796               "Question: Are you a boy or a girl?"      0
8797  "Leave your email or phone number and maybe yo...      1
8798  "From the scenarios you present, I see you bel...      0

[8799 rows x 2 columns]

In [12]:
# kaggle_clean.shape
kaggle_clean.isna().sum()

Text     0
label    0
dtype: int64

In [13]:
kaggle_clean['Text']

0                                    "You fuck your dad."
1       "i really don't understand your point.\xa0 It ...
2       "A\\xc2\\xa0majority of Canadians can and has ...
3       "listen if you dont wanna get married to a man...
4       "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...
                              ...
8794    "Never really gave it much thought. I just fig...
8795                   "Nadie se salva de la regla 34 xd"
8796                 "Question: Are you a boy or a girl?"
8797    "Leave your email or phone number and maybe yo...
8798    "From the scenarios you present, I see you bel...
Name: Text, Length: 8799, dtype: object

In [14]:
#trying to download the cleaned dataset
kaggle_clean

                                                   Text  label
0                                  "You fuck your dad."      1
1     "i really don't understand your point.\xa0 It ...      0
2     "A\\xc2\\xa0majority of Canadians can and has ...      0
3     "listen if you dont wanna get married to a man...      0
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...      0
...                                                 ...    ...
8794  "Never really gave it much thought. I just fig...      0
8795                 "Nadie se salva de la regla 34 xd"      0
8796               "Question: Are you a boy or a girl?"      0
8797  "Leave your email or phone number and maybe yo...      1
8798  "From the scenarios you present, I see you bel...      0

[8799 rows x 2 columns]

In [15]:
kaggle_clean['Text']

0                                    "You fuck your dad."
1       "i really don't understand your point.\xa0 It ...
2       "A\\xc2\\xa0majority of Canadians can and has ...
3       "listen if you dont wanna get married to a man...
4       "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...
                              ...
8794    "Never really gave it much thought. I just fig...
8795                   "Nadie se salva de la regla 34 xd"
8796                 "Question: Are you a boy or a girl?"
8797    "Leave your email or phone number and maybe yo...
8798    "From the scenarios you present, I see you bel...
Name: Text, Length: 8799, dtype: object

In [16]:
# now genarating a function

import re

def clean_text(data):

  result0 = re.sub(r'x[a-z0-9\s]+[\d]+'," ",data)

  # checking
  result = re.sub(r'https?[\S]+', " ", result0)
  partiallycleaned_result=result
  partiallycleaned_result

  #checking
  fully_cleaned_result=re.sub(r' @[a-zA-Z0-9]+'," ",partiallycleaned_result)
  fully_cleaned_result

 #remove special characters
  fully_cleaned_result = re.sub(r'\W+'," ",fully_cleaned_result)
  cleaned_data= fully_cleaned_result.strip().lower()
  return cleaned_data


#passing data to the function

# data="@ShreyaBafna3 You are SO stupid!! Check http://somelink.com \xc2\xa0"
data="Check http://somelink.com you are stupid /xa0 1212 "
clean_text(data)

'check you are stupid'

In [17]:
kaggle_clean['Text'] = kaggle_clean['Text'].apply(clean_text)

In [18]:
kaggle_clean['Text']

0                                       you fuck your dad
1       i really don t understand your point it seems ...
2       a majority of canadians can and has been wrong...
3       listen if you dont wanna get married to a man ...
4       c c b u1ea1n xu u1ed1ng u0111 u01b0 u1eddng bi...
                              ...
8794    never really gave it much thought i just figur...
8795                     nadie se salva de la regla 34 xd
8796                     question are you a boy or a girl
8797    leave your email or phone number and maybe you...
8798    from the scenarios you present i see you belie...
Name: Text, Length: 8799, dtype: object

In [19]:
kaggle_clean.head()

                                                Text  label
0                                  you fuck your dad      1
1  i really don t understand your point it seems ...      0
2  a majority of canadians can and has been wrong...      0
3  listen if you dont wanna get married to a man ...      0
4  c c b u1ea1n xu u1ed1ng u0111 u01b0 u1eddng bi...      0

In [20]:
kaggle_clean['Text'][8798]

'from the scenarios you present i see you believe all people are robots abraham no matter his environment or upbringing chose to aim his gun at the poor guy he killed and he chose to pull the trigger he has a bad childhood so let s understand why he would kill someone nwhen he s older he doesn t have the sense to realize that going before the judge you might want to appear humble and show some respect two things by the way that wasn t taught to him as a child and appears as a man is not important to him again his choice nhe knows selling drugs is wrong and could land him back in jail again a stupid premeditated decision on his part and he will be in jail shortly after he gets out because that s what a stupid unteachable hardened piece of clay does turn down the same road n nand you re right i am saying all this from my perspective like i said in my other comment most people could be put in abraham s exact shoes and they won t raise a gun and shoot that poor man dead nhumans not robots'

importing nltk libraries for text stopword removal

In [21]:
import nltk

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Modifyig the regex function by adding stpword removal from nltk

In [22]:

def clean_text(data):
  if data is None:
        return ""

  result0 = re.sub(r'x[a-z0-9\s]+[\d]+'," ",data)
  # checking
  result = re.sub(r'https?[\S]+', " ", result0)
  partiallycleaned_result=result
  partiallycleaned_result
  #checking
  fully_cleaned_result=re.sub(r' @[a-zA-Z0-9]+'," ",partiallycleaned_result)
  fully_cleaned_result
  #remove special characters
  fully_cleaned_result = re.sub(r'\W+'," ",fully_cleaned_result)
  cleaned_data = fully_cleaned_result.strip().lower()
  # return cleaned_data
  # print(f"No stopword removal : {cleaned_data}")

  #getting set of english stopwords for efficient look up
  stop_words = set(stopwords.words('english'))
  word_tokens = [word for word in word_tokenize(cleaned_data)]
  filtered_sentence = [word for word in word_tokens if word not in stop_words]
  filtered_text = " ".join(filtered_sentence)

  #returnes filtered data with no stopwords
  # print(f"After stopword removal : {filtered_text}")
  return filtered_text
  #passing data to the function

# data="@ShreyaBafna3 You are SO stupid!! Check http://somelink.com \xc2\xa0"
# data="you are so stupid and the world is a bad place"
# clean_text(data)

In [23]:
kaggle_clean['Text']=kaggle_clean['Text'].apply(clean_text)

In [24]:
kaggle_clean.head()

                                                Text  label
0                                           fuck dad      1
1  really understand point seems mixing apples or...      0
2  majority canadians wrong n nunless supportive ...      0
3  listen dont wan na get married man women dont ...      0
4                                       c c b u1ea1n      0

added a vietnamese filter (removes too short after cleaning,non-english,and empty rows)

In [25]:
kaggle_clean = kaggle_clean[kaggle_clean['Text'].str.split().str.len() > 3]
print("Final shape:", kaggle_clean.shape)

Final shape: (7275, 2)

In [26]:
kaggle_clean.head()

                                                Text  label
1  really understand point seems mixing apples or...      0
2  majority canadians wrong n nunless supportive ...      0
3  listen dont wan na get married man women dont ...      0
4                                       c c b u1ea1n      0
5  sdl ok would hope sign one year contract start...      0

dowloading the dataset cleaned one

In [27]:
kaggle_clean.to_csv('kaggle_cleaned.csv', index=False)

In [28]:
from google.colab import files
files.download('kaggle_cleaned.csv')

TF-IDF

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer= TfidfVectorizer() # vectorizer object made of TfidfVectorizer() class.  Vectorizing is converting words into numbers.
X=vectorizer.fit_transform(kaggle_clean['Text']) #fit-> learn properties of data, transform->apply learned parameters.
print(vectorizer.get_feature_names_out())
print(X.shape)

['00' '000' '004' ... 'zuma' 'zusammenschmei' 'zzzzzzzzzzzzzzzzzzzzz']
(7275, 21972)

In [30]:
kaggle_clean['label']

1       0
2       0
3       0
4       0
5       0
       ..
8793    0
8794    0
8795    0
8797    1
8798    0
Name: label, Length: 7275, dtype: int64

Importing Train and Test

In [31]:
from sklearn.model_selection import train_test_split
y= kaggle_clean['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
#shape of X_train and X_test
# X_train.shape
# X_test.shape
# y_train.shape
# y_test.shape

In [33]:
X_test.shape

(1455, 21972)

Using Logistic Regression

In [34]:
from sklearn.linear_model import LogisticRegression
clf_log=LogisticRegression()
clf_log.fit(X_train,y_train)
clf_log.predict(X_test)

array([0, 0, 0, ..., 0, 0, 1])

In [35]:
#checking accuracy
clf_log.score(X_test,y_test)

0.7766323024054983

In [36]:
#checking f1 score
from sklearn.metrics import f1_score
f1_score(y_test, clf_log.predict(X_test))

0.48657187993680884

Using Multinomial NaiveBayes

In [37]:
from sklearn.naive_bayes import MultinomialNB
clf_MNB=MultinomialNB()
clf_MNB.fit(X_train,y_train)
clf_MNB.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [38]:
#accuracy
clf_MNB.score(X_test,y_test)

0.718213058419244

In [39]:
#f1 score
f1_score(y_test,clf_MNB.predict(X_test))

0.19291338582677164

Using SVM

In [40]:
from sklearn import svm
clf_svm=svm.SVC(kernel='linear')
clf_svm.fit(X_train,y_train)
clf_svm.predict(X_test)

array([0, 0, 1, ..., 0, 0, 1])

In [41]:
#accuracy
clf_svm.score(X_test,y_test)

0.8034364261168385

In [42]:
#f1-score
f1_score(y_test,clf_svm.predict(X_test))

0.6114130434782609

Random Forest

In [43]:
from sklearn.ensemble import RandomForestClassifier
clf_RF = RandomForestClassifier()
clf_RF.fit(X_train,y_train)
clf_RF.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [44]:
#accucracy
clf_RF.score(X_test,y_test)

0.7896907216494845

In [45]:
#f1-score
f1_score(y_test,clf_RF.predict(X_test))

0.5616045845272206

BERT

In [46]:
!pip install transformers torch

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.4.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [47]:
from transformers import pipeline

In [48]:
from transformers import BertTokenizer, BertForSequenceClassification
from torch.utils.data import Dataset, DataLoader
import torch

print("All imports successful!")

All imports successful!

In [49]:
from sklearn.model_selection import train_test_split

# Use cleaned text and labels from kaggle_clean
texts = kaggle_clean['Text'].tolist()
labels = kaggle_clean['label'].tolist()

# Split 80/20 same as before
train_texts, test_texts, train_labels, test_labels = train_test_split(
    texts, labels, test_size=0.2, random_state=42
)

print("Train size:", len(train_texts))
print("Test size:", len(test_texts))

Train size: 5820
Test size: 1455

Now tokenizer load garau. BERT le text directly padhdaina — pehila tokenize garchha, matlab text lai special number sequences ma convert garchha.

In [50]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=128)

print("Tokenization done!")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Tokenization done!

Perfect. Warning haru ignore gar — tyo just authentication ko kura ho, kaam garnama affect gardaina.
Now PyTorch Dataset banau. BERT lai data specific format ma dinu parcha:
New cell ma type gar:

In [51]:
class CyberbullyingDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

train_dataset = CyberbullyingDataset(train_encodings, train_labels)
test_dataset = CyberbullyingDataset(test_encodings, test_labels)

print("Datasets created!")
print("Train size:", len(train_dataset))
print("Test size:", len(test_dataset))

Datasets created!
Train size: 5820
Test size: 1455

In [52]:
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)
print("Model loaded!")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model loaded!

In [53]:
from torch.optim import AdamW

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print("Using device:", device)

model.to(device)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

optimizer = AdamW(model.parameters(), lr=2e-5)

print("Training setup done!")

Using device: cuda
Training setup done!

In [54]:
from tqdm import tqdm

model.train()
for epoch in range(3):
    total_loss = 0
    for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        total_loss += loss.item()

        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1} complete. Avg Loss: {total_loss/len(train_loader):.4f}")

print("Training complete!")

Epoch 1: 100%|██████████| 364/364 [01:57<00:00,  3.10it/s]

Epoch 1 complete. Avg Loss: 0.4774

Epoch 2: 100%|██████████| 364/364 [02:03<00:00,  2.95it/s]

Epoch 2 complete. Avg Loss: 0.3305

Epoch 3: 100%|██████████| 364/364 [02:07<00:00,  2.86it/s]

Epoch 3 complete. Avg Loss: 0.1780
Training complete!

In [55]:

from sklearn.metrics import accuracy_score, f1_score

model.eval()
all_preds = []
all_labels = []

with torch.no_grad():
    for batch in tqdm(test_loader, desc="Evaluating"):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids, attention_mask=attention_mask)
        preds = torch.argmax(outputs.logits, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

accuracy = accuracy_score(all_labels, all_preds)
f1 = f1_score(all_labels, all_preds)

print(f"BERT Accuracy: {accuracy:.4f}")
print(f"BERT F1 Score: {f1:.4f}")

Evaluating: 100%|██████████| 91/91 [00:11<00:00,  8.12it/s]

BERT Accuracy: 0.8082
BERT F1 Score: 0.6990

In [56]:
import pandas as pd

results = {
    'Model': ['Logistic Regression', 'Naive Bayes', 'SVM', 'Random Forest', 'BERT'],
    'Accuracy': [0.7766, 0.7182, 0.8034, 0.7883, 0.8014],
    'F1 Score': [0.4866, 0.1929, 0.6114, 0.5484, 0.7030]
}

results_df = pd.DataFrame(results)
results_df = results_df.sort_values('F1 Score', ascending=False).reset_index(drop=True)
print(results_df.to_string(index=False))

              Model  Accuracy  F1 Score
               BERT    0.8014    0.7030
                SVM    0.8034    0.6114
      Random Forest    0.7883    0.5484
Logistic Regression    0.7766    0.4866
        Naive Bayes    0.7182    0.1929

joblib() saving for svm

In [57]:
print(kaggle_clean.shape)

(7275, 2)

In [58]:
print(kaggle_clean.shape)

(7275, 2)

In [59]:
pip install joblib

Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)

In [62]:
import joblib

joblib.dump(clf_svm,'clf_svm.joblib')

['clf_svm.joblib']

Load a Model

In [76]:
import joblib
clf_loaded_svm= joblib.load('clf_svm.joblib')
predictions = clf_loaded_svm.predict(X_test)

joblib() saving for logistic regresion

In [75]:
import joblib
joblib.dump(clf_log,'clf_log.joblib')
clf_loaded_log=joblib.load('clf_log.joblib')
predictions =clf_loaded_log.predict(X_test)

For Random Forest

In [74]:
joblib.dump(clf_RF,'clf_RF.joblib')
clf_loaded_RF=joblib.load('clf_RF.joblib')
predictions =clf_loaded_RF.predict(X_test)

For Multinomial Naive Bayes

In [73]:
joblib.dump(clf_MNB,'clf_MNB.joblib')
clf_loaded_MNB=joblib.load('clf_MNB.joblib')
predictions =clf_loaded_MNB.predict(X_test)

In [77]:
joblib.dump(vectorizer, 'vectorizer.joblib')

['vectorizer.joblib']

In [2]:
# from google.colab import files
# files.download('clf_svm.joblib')
# files.download('clf_log.joblib')
# files.download('clf_RF.joblib')
# files.download('clf_MNB.joblib')
# files.download('vectorizer.joblib')