<a href="https://colab.research.google.com/github/jenous11/CRUD-application-in-php/blob/main/workingwithkaggle_parsed_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from google.colab import files
uploaded_files=files.upload()

Saving kaggle_parsed_dataset.csv to kaggle_parsed_dataset.csv

In [4]:
kaggle_df=pd.read_csv("kaggle_parsed_dataset.csv")

In [5]:
kaggle_df.head(5)

,index,oh_label,Date,Text
0,0,1,20120618192155Z,"""You fuck your dad."""
1,1,0,20120528192215Z,"""i really don't understand your point.\xa0 It ..."
2,2,0,NaN,"""A\\xc2\\xa0majority of Canadians can and has ..."
3,3,0,NaN,"""listen if you dont wanna get married to a man..."
4,4,0,20120619094753Z,"""C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd..."

In [6]:
kaggle_df.isnull().sum()

index          0
oh_label       0
Date        1242
Text           0
dtype: int64

In [7]:
print(kaggle_df.shape)

(8799, 4)

In [8]:
# checking for missing data

print("Missing Text:", kaggle_df['Text'].isna().sum())
print("\nLabel distribution:\n")
print(kaggle_df['oh_label'].value_counts())

Missing Text: 0

Label distribution:

oh_label
0    5993
1    2806
Name: count, dtype: int64

In [9]:
#cleaning the empty cells

In [10]:
kaggle_clean=kaggle_df[['Text','oh_label']].copy()

In [11]:
# kaggle_clean=kaggle_clean.dropna(subset=['Text','oh_label'])
kaggle_clean=kaggle_clean.dropna(subset=['Text','oh_label'])
kaggle_clean

                                                   Text  oh_label
0                                  "You fuck your dad."         1
1     "i really don't understand your point.\xa0 It ...         0
2     "A\\xc2\\xa0majority of Canadians can and has ...         0
3     "listen if you dont wanna get married to a man...         0
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...         0
...                                                 ...       ...
8794  "Never really gave it much thought. I just fig...         0
8795                 "Nadie se salva de la regla 34 xd"         0
8796               "Question: Are you a boy or a girl?"         0
8797  "Leave your email or phone number and maybe yo...         1
8798  "From the scenarios you present, I see you bel...         0

[8799 rows x 2 columns]

In [12]:
kaggle_clean=kaggle_clean.rename(columns={'oh_label':'label'})
kaggle_clean

                                                   Text  label
0                                  "You fuck your dad."      1
1     "i really don't understand your point.\xa0 It ...      0
2     "A\\xc2\\xa0majority of Canadians can and has ...      0
3     "listen if you dont wanna get married to a man...      0
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...      0
...                                                 ...    ...
8794  "Never really gave it much thought. I just fig...      0
8795                 "Nadie se salva de la regla 34 xd"      0
8796               "Question: Are you a boy or a girl?"      0
8797  "Leave your email or phone number and maybe yo...      1
8798  "From the scenarios you present, I see you bel...      0

[8799 rows x 2 columns]

In [13]:
# kaggle_clean.shape
kaggle_clean.isna().sum()

Text     0
label    0
dtype: int64

In [14]:
kaggle_clean['Text']

0                                    "You fuck your dad."
1       "i really don't understand your point.\xa0 It ...
2       "A\\xc2\\xa0majority of Canadians can and has ...
3       "listen if you dont wanna get married to a man...
4       "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...
                              ...
8794    "Never really gave it much thought. I just fig...
8795                   "Nadie se salva de la regla 34 xd"
8796                 "Question: Are you a boy or a girl?"
8797    "Leave your email or phone number and maybe yo...
8798    "From the scenarios you present, I see you bel...
Name: Text, Length: 8799, dtype: object

In [15]:
kaggle_clean['Text']

0                                    "You fuck your dad."
1       "i really don't understand your point.\xa0 It ...
2       "A\\xc2\\xa0majority of Canadians can and has ...
3       "listen if you dont wanna get married to a man...
4       "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...
                              ...
8794    "Never really gave it much thought. I just fig...
8795                   "Nadie se salva de la regla 34 xd"
8796                 "Question: Are you a boy or a girl?"
8797    "Leave your email or phone number and maybe yo...
8798    "From the scenarios you present, I see you bel...
Name: Text, Length: 8799, dtype: object

In [16]:
# now genarating a function

import re

def clean_text(data):

  # checking for url links
  result = re.sub(r'https?[\S\s]+', " ", data)
  partiallycleaned_result=result
  partiallycleaned_result

  #checking for new @ and other mentions
  fully_cleaned_result=re.sub(r'@[a-zA-Z0-9]+'," ",partiallycleaned_result)
  fully_cleaned_result

# #remove special characters
  fully_cleaned_result = re.sub(r'\W+'," ",fully_cleaned_result)
  cleaned_data= fully_cleaned_result.strip().lower()
  return cleaned_data

# output:"you are so stupid check"


#passing data to the function
# data="@ShreyaBafna3 You are SO stupid!! Check http://somelink.com \xc2\xa0"
# clean_text(data)

'you are so stupid check'

In [20]:
kaggle_clean['Text'] = kaggle_clean['Text'].apply(clean_text)

In [21]:
kaggle_clean['Text']

0                                       you fuck your dad
1       i really don t understand your point xa0 it se...
2       a xc2 xa0majority of canadians can and has bee...
3       listen if you dont wanna get married to a man ...
4       c xe1c b u1ea1n xu u1ed1ng u0111 u01b0 u1eddng...
                              ...
8794    never really gave it much thought i just figur...
8795                     nadie se salva de la regla 34 xd
8796                     question are you a boy or a girl
8797    leave your email or phone number and maybe you...
8798    from the scenarios you present i see you belie...
Name: Text, Length: 8799, dtype: object

In [22]:
kaggle_clean.head()

                                                Text  label
0                                  you fuck your dad      1
1  i really don t understand your point xa0 it se...      0
2  a xc2 xa0majority of canadians can and has bee...      0
3  listen if you dont wanna get married to a man ...      0
4  c xe1c b u1ea1n xu u1ed1ng u0111 u01b0 u1eddng...      0